namespace Casimodo.Mojen
{
    public class TsGenBase : DataLayerGenerator
    {
        protected override void OGeneratedFileDeclaration()
        {
            O("// NOTE: This file was generated by the Casimodo.Mojen tool. Manual changes will be overwritten.");
            O("/* eslint-disable semi */");
            O("/* eslint-disable no-multiple-empty-lines */");
            O("/* eslint-disable @typescript-eslint/no-empty-object-type */");
            O();
        }
    }
}